# Generated by Django 5.0.4 on 2024-04-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('event', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
